export const UPDATED_CELL = 'UPDATED_CELL';
export const PUSHED_CELL_TO_STACK = 'PUSHED_CELL_TO_STACK';
export const POPPED_CELL_FROM_STACK = 'POPPED_CELL_FROM_STACK';
export const CLEAR_GRID = 'CLEAR_GRID';
export const SET_INTERVAL = 'SET_INTERVAL';
